
services:
  product-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-app
    image: linktic-product-app:1.0.0
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/ORCLPDB1
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: oracle
    depends_on:
      - oracle-db
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
